## Documentation: http://docs.travis-ci.com/user/languages/julia/
codecov: true
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - nightly
branches:
  only:
    - master
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')  
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("InfrastructureSensing")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

