## Documentation: http://docs.travis-ci.com/user/languages/julia/
codecov: true
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - nightly
branches:
  only:
    - master
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.4 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
notifications:
  email: false
